import "./globals.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";

import type { Metadata } from "next";
import Header from "@/components/header";
import Footer from "@/components/footer";
import ReactQueryProvider from "@/components/provider/react-query";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark bg-primary-foreground">
        <ReactQueryProvider>
          <div className="min-h-dvh flex flex-col">
            <Header />
            {children}
            <Footer />
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
